apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam
  labels:
    app: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam
  template:
    metadata:
      labels:
        app: exam
    spec:
      containers:
      - name: exam
        image: hapra123/node_019:latest
        ports:
        - containerPort: 3000 
