apiVersion: v1
kind: Service
metadata:
  labels:
    app: exam
  name: exam
spec:
  type: NodePort
  selector:
    app: exam
  ports:
    - port: 3000           
      targetPort: 3000     
      protocol: TCP
